spring.application.name=asset

server.port=8080

spring.web.favicon.enabled=false

spring.datasource.url=jdbc:mysql://123.56.77.151:3306/ai?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false
spring.datasource.username=root
spring.datasource.password=wlz123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:com.wlz.asset/mapper/*.xml

# huoshan, zhipu
ai.provider=deepseek

ai.huoshan.api-url=https://ark.cn-beijing.volces.com/api/v3/chat/completions
ai.huoshan.api-key=2f2bf74a-8699-4b8e-b7a8-c15d256e2f76
ai.huoshan.model=doubao-seed-2-0-pro-260215

ai.zhipu.api-url=https://open.bigmodel.cn/api/paas/v4/chat/completions
ai.zhipu.api-key=ffab6263dcd348fb9d67c405dd3b6885.5INs959ExG7pwnGP
ai.zhipu.model=glm-5

ai.deepseek.api-url=https://api.deepseek.com/chat/completions
ai.deepseek.api-key=sk-19f86928ce2b48ebb1f03c71405aa91c
ai.deepseek.model=deepseek-reasoner

ai.openai.api-url=https://api.deepseek.com/chat/completions
ai.openai.api-key=
ai.openai.model=deepseek-reasoner

ai.gemini.api-url=https://openrouter.ai/api/v1/chat/completions
ai.gemini.api-key=
ai.gemini.model=anthropic/claude-opus-4.6
